import type { ProductSearchResult } from "@/lib/productSearch";

export type StorefrontPromptProduct = Pick<
  ProductSearchResult,
  | "sku"
  | "name"
  | "brand"
  | "category"
  | "price"
  | "palette"
  | "imageDataUri"
  | "tags"
>;

export function formatStorefrontPrice(price: number) {
  return `$${price.toFixed(2)}`;
}

function toPromptProduct(product: StorefrontPromptProduct) {
  return {
    sku: product.sku,
    name: product.name,
    brand: product.brand,
    category: product.category,
    price: formatStorefrontPrice(product.price),
    palette: product.palette,
    imageDataUri: product.imageDataUri,
    tags: product.tags.slice(0, 5)
  };
}

export function buildCodexStorefrontPrompt({
  trend,
  products
}: {
  trend: string;
  products: StorefrontPromptProduct[];
}) {
  const productsJson = JSON.stringify(products.map(toPromptProduct));

  return `You are Codex running inside the Trend Mall web app. Generate code for a customer-facing storefront.

Input trend:
${trend}

Products, as JSON:
${productsJson}

Return exactly one complete HTML document. Do not return markdown. Do not explain.

Hard constraints:

- Output must start with <!doctype html>.
- Use only HTML and inline CSS inside a <style> tag.
- Do not use JavaScript.
- Do not include <script>, <iframe>, <object>, <embed>, <form>, external stylesheets, external fonts, analytics, fetch calls, or network requests.
- Use only the product data provided.
- Product images are data URIs; preserve them exactly.
- Include every selected product exactly once.
- Include prices exactly as provided.
- Make the page responsive.
- The storefront should look bold, editorial, and screenshot-worthy, not like a generic template.
- The creative direction must strongly express the trend.
- Keep the code compact: one style block, no comments, no duplicated product data, and fewer than 9000 characters when possible.

Required structure:

1. Hero section with a vivid campaign name.
2. One-sentence “why this mall shelf exists” copy.
3. Product grid with cards.
4. Each product card must include image, name, price, category, and a trend-specific micro-pitch.
5. A checkout CTA section that treats the shelf as purchasable and ready to add to cart.
6. The checkout CTA should feel click-worthy on video: use an anchor link with a longer CSS :target or :active animation where small product tiles fly into the add-to-cart button, with no JavaScript. Reserve enough vertical space for the CTA and animation so the button and animated items never overlap the headline or body copy.
7. A small data-URI SVG favicon link for Trend Mall.
8. A small footer: “Generated by Codex for Trend Mall”.

Layout variety:

- Pick exactly one layout archetype based on the trend, then commit to it throughout the page.
- Use the chosen archetype to influence composition, spacing, typography, borders, product framing, and CTA treatment.
- Choose from: magazine spread, toy catalog, luxury drop, arcade shelf, birthday party table, streetwear launch, airport essentials board, cozy home edit, founder desk kit, or night-market wall.
- Do not mention the archetype name in user-facing copy unless it naturally fits the campaign.

Design goal:
Make this feel like a polished, social-shareable retail campaign with a clear reveal moment, oversized campaign type, and visually dominant product imagery. Prioritize returning valid code quickly over adding extra ornament.`;
}
