import { describe, expect, it } from "vitest";

import { validateGeneratedStorefrontHtml } from "./htmlSafety";
import type { StorefrontPromptProduct } from "./codex/prompt";

const products: StorefrontPromptProduct[] = [
  {
    sku: "TM-001",
    name: "Cloud Pop Birthday Hoodie",
    brand: "Trend Mall",
    category: "apparel",
    price: 42,
    palette: ["#ffccdd", "#3157a4"],
    imageDataUri: "data:image/svg+xml,%3Csvg%3E%3C/svg%3E",
    tags: ["birthday", "cute"]
  }
];

function validHtml(extra = "") {
  return `<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>Cloud Pop Shelf</title>
    <style>body { font-family: system-ui; }</style>
  </head>
  <body>
    ${extra}
    <main>
      <h1>Cloud Pop Shelf</h1>
      <article>
        <img src="${products[0].imageDataUri}" alt="" />
        <h2>Cloud Pop Birthday Hoodie</h2>
        <p>apparel</p>
        <p>$42.00</p>
      </article>
      <footer>Generated by Codex for Trend Mall</footer>
    </main>
  </body>
</html>`;
}

describe("validateGeneratedStorefrontHtml", () => {
  it("accepts a valid generated storefront", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml(),
      products
    });

    expect(result.ok).toBe(true);
    expect(result.ok && result.title).toBe("Cloud Pop Shelf");
  });

  it("accepts inline CSS and data URI product images", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml("<style>.campaign { color: #151515; }</style>"),
      products
    });

    expect(result.ok).toBe(true);
    expect(result.ok && result.html).toContain(products[0].imageDataUri);
  });

  it("rejects script tags", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml("<script>alert('x')</script>"),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include script tags."
    });
  });

  it("rejects inline event handlers", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml('<a onclick="alert(1)">Buy</a>'),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include inline event handlers."
    });
  });

  it("rejects forms", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml("<form><input /></form>"),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include form tags."
    });
  });

  it.each([
    ["iframe", "Generated HTML cannot include iframe tags."],
    ["object", "Generated HTML cannot include object tags."],
    ["embed", "Generated HTML cannot include embed tags."]
  ])("rejects %s tags", (tag, error) => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml(`<${tag}></${tag}>`),
      products
    });

    expect(result).toEqual({
      ok: false,
      error
    });
  });

  it("rejects javascript URLs", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml('<a href="javascript:alert(1)">Buy</a>'),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include javascript: URLs."
    });
  });

  it("rejects external stylesheet links", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml('<link rel="stylesheet" href="https://cdn.example.com/store.css" />'),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include external stylesheet links."
    });
  });

  it("rejects external font links", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml('<link rel="preconnect" href="https://fonts.example.com" />'),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include external font or stylesheet links."
    });
  });

  it("rejects external CSS URLs", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml(
        '<style>.hero { background-image: url("https://cdn.example.com/hero.png"); }</style>'
      ),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML cannot include external CSS URLs."
    });
  });

  it("rejects HTML that omits selected product names", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml().replace("Cloud Pop Birthday Hoodie", "Mystery Hoodie"),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML is missing selected product name: Cloud Pop Birthday Hoodie."
    });
  });

  it("rejects HTML that omits selected product prices", () => {
    const result = validateGeneratedStorefrontHtml({
      html: validHtml().replace("$42.00", "$41.00"),
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated HTML is missing selected product price: $42.00."
    });
  });

  it("rejects markdown-only output", () => {
    const result = validateGeneratedStorefrontHtml({
      html: "```html\n<p>Cloud Pop Birthday Hoodie $42.00</p>\n```",
      products
    });

    expect(result).toEqual({
      ok: false,
      error: "Generated output must be one complete HTML document, not markdown or a fragment."
    });
  });
});
