import Link from "next/link";
import Image from "next/image";
import { notFound, redirect } from "next/navigation";

import { PublishStorefrontPanel } from "@/components/PublishStorefrontPanel";
import { canEditStorefront, getCurrentUser } from "@/lib/auth";
import { getStorefrontPageAccess } from "@/lib/storefrontAccess";
import { findStorefrontByIdOrSlug } from "@/lib/storefronts";
import {
  getStorefrontEmbedPath,
  getStorefrontEmbedUrl,
  getStorefrontShareUrl
} from "@/lib/storefrontUrls";

type StorefrontPageProps = {
  params: Promise<{
    id: string;
  }>;
};

function formatDate(date: Date) {
  return new Intl.DateTimeFormat("en", {
    dateStyle: "medium",
    timeStyle: "short"
  }).format(date);
}

function formatPrice(price: number) {
  return `$${price.toFixed(2)}`;
}

const technicalBadges = [
  "Codex SDK server-side",
  "Atlas autoEmbed catalog search",
  "Code safety validation",
  "Strict iframe sandbox",
  "MongoDB persisted"
];

export default async function StorefrontPage({ params }: StorefrontPageProps) {
  const { id } = await params;
  const user = await getCurrentUser();
  const storefront = await findStorefrontByIdOrSlug(id);

  if (!storefront) {
    notFound();
  }

  const access = getStorefrontPageAccess(storefront, user);

  if (access === "login") {
    redirect(`/login?next=/storefronts/${encodeURIComponent(id)}&message=auth_required`);
  }

  if (access === "hidden") {
    notFound();
  }

  const isOwner = canEditStorefront(user?._id, storefront);
  const publicUrl = getStorefrontShareUrl(storefront);
  const embedPath = getStorefrontEmbedPath(storefront);
  const embedUrl = getStorefrontEmbedUrl(storefront);

  return (
    <main className="page">
      <section className="storefront-share-layout">
        <div>
          <p className="eyebrow">Storefront share page</p>
          <h1>{storefront.title}</h1>
          <p className="lede">
            {storefront.status === "published"
              ? "This published storefront is public."
              : "You are viewing your own private draft."}{" "}
            Generated code is rendered only through the authorized sandboxed
            embed route.
          </p>
          <div className="technical-badges" aria-label="Technical proof points">
            {technicalBadges.map((badge) => (
              <span className="status-pill" key={badge}>
                {badge}
              </span>
            ))}
          </div>
          <div className="storefront-meta-grid">
            <div>
              <span>Vibe</span>
              <strong>{storefront.vibe}</strong>
            </div>
            <div>
              <span>Generated</span>
              <strong>{formatDate(storefront.createdAt)}</strong>
            </div>
            <div>
              <span>Status</span>
              <strong>{storefront.status}</strong>
            </div>
            {storefront.publishedAt ? (
              <div>
                <span>Published</span>
                <strong>{formatDate(storefront.publishedAt)}</strong>
              </div>
            ) : null}
          </div>
          <div className="button-row">
            <Link className="button secondary" href="/mall">
              Back to Mall
            </Link>
            <Link className="button secondary" href={embedPath}>
              View embed
            </Link>
          </div>
          {storefront.generatedHtml.trim() ? (
            <div className="iframe-shell storefront-page-frame share-page-preview">
              <div className="preview-toolbar">
                <span />
                <span />
                <span />
                <p>Sandboxed generated storefront</p>
              </div>
              <iframe
                sandbox=""
                src={embedPath}
                title={`${storefront.title} generated storefront`}
              />
            </div>
          ) : null}
        </div>
        <aside className="storefront-side-rail">
          <div className="panel">
            <span className="status-pill">Sandboxed code generated by Codex</span>
            <h2>Safe preview boundary</h2>
            <p>
              The generated document is served from the embed route and rendered
              in an iframe without script, form, or same-origin permissions.
            </p>
          </div>
          <PublishStorefrontPanel
            canPublish={isOwner && storefront.status === "draft"}
            initialEmbedUrl={storefront.status === "published" ? embedUrl : undefined}
            initialPublicUrl={storefront.status === "published" ? publicUrl : undefined}
            initialStatus={storefront.status}
            storefrontId={storefront._id.toHexString()}
          />
          <div className="panel">
            <p className="eyebrow">Products used</p>
            <h2>{storefront.productsSnapshot.length} catalog picks</h2>
            <div className="snapshot-list">
              {storefront.productsSnapshot.map((product) => (
                <article className="snapshot-row" key={product._id.toHexString()}>
                  <Image
                    alt=""
                    height={56}
                    src={product.imageDataUri}
                    unoptimized
                    width={56}
                  />
                  <div>
                    <h3>{product.name}</h3>
                    <p>
                      {product.category} · {formatPrice(product.price)}
                    </p>
                    <div className="tag-row compact">
                      {product.tags.slice(0, 3).map((tag) => (
                        <span key={tag}>{tag}</span>
                      ))}
                    </div>
                  </div>
                </article>
              ))}
            </div>
          </div>
          <div className="panel">
            <span className="status-pill">{storefront.status}</span>
            <h2>Access rule enforced</h2>
            <p>
              Published storefronts are public. Draft storefronts are only
              visible to their owner.
            </p>
          </div>
        </aside>
      </section>
    </main>
  );
}
